query Bags($skip: Int, $first: Int) {
    bags(skip: $skip, first: $first) {
        id
        name
        owner {
            id
            username
            name
        }
    }
    _bagsMeta {
        count
    }
}

query GetBagKits($bag: ID!) {
    getBagKits(bag: $bag) {
        id
        type
        name
        owner
        items {
            itemId
            qty
        }
    }
}
